#!/usr/bin/env ruby
case ARGV[0]
when 'on','start'
	`osascript -e 'tell application "Caffeine" to turn on'`
	puts 'Setting caffeine to on'
when 'off','stop'
	`osascript -e 'tell application "Caffeine" to turn off'`
	puts 'Setting caffeine to off'
else
	puts 'Caffeine is '+`osascript -e 'tell application "Caffeine" to get active'`
end